module.exports = {
  PRE_GENERAL_NURTURE: "PRE_GENERAL_NURTURE",
  SOLO_FOUNDATION: "SOLO_FOUNDATION",
  SOLO_LEAD_ENGINE: "SOLO_LEAD_ENGINE",
  SOLO_PIPELINE_REPAIR: "SOLO_PIPELINE_REPAIR",
  SOLO_SCALE_25: "SOLO_SCALE_25",
};
